config/routes.rb
Xnwx::Application.routes.draw do

  resources :games
  resources :game_sources

  resources :bells
  resources :tags

  root :to => 'welcome#index'

end

app/models/game_source.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: game_sources
#
#  id          :integer          not null, primary key
#  game_id     :integer
#  source_url  :string(255)
#  source_name :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

# -*- encoding : utf-8 -*-
class GameSource < ActiveRecord::Base
  belongs_to :games
  attr_accessible :source_name, :source_url
end

app/controllers/game_sources_controller.rb
# -*- encoding : utf-8 -*-
class GameSourcesController < ApplicationController
  # GET /game_sources
  # GET /game_sources.json
  def index
    @game_sources = GameSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @game_sources }
    end
  end

  # GET /game_sources/1
  # GET /game_sources/1.json
  def show
    @game_source = GameSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game_source }
    end
  end

  # GET /game_sources/new
  # GET /game_sources/new.json
  def new
    @game_source = GameSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game_source }
    end
  end

  # GET /game_sources/1/edit
  def edit
    @game_source = GameSource.find(params[:id])
  end

  # POST /game_sources
  # POST /game_sources.json
  def create
    @game_source = GameSource.new(params[:game_source])

    respond_to do |format|
      if @game_source.save
        format.html { redirect_to @game_source, notice: 'Game source was successfully created.' }
        format.json { render json: @game_source, status: :created, location: @game_source }
      else
        format.html { render action: "new" }
        format.json { render json: @game_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /game_sources/1
  # PUT /game_sources/1.json
  def update
    @game_source = GameSource.find(params[:id])

    respond_to do |format|
      if @game_source.update_attributes(params[:game_source])
        format.html { redirect_to @game_source, notice: 'Game source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_sources/1
  # DELETE /game_sources/1.json
  def destroy
    @game_source = GameSource.find(params[:id])
    @game_source.destroy

    respond_to do |format|
      format.html { redirect_to game_sources_url }
      format.json { head :no_content }
    end
  end
end

app/views/game_sources/_form.html.erb
<%= form_for(@game_source) do |f| %>
  <% if @game_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_source.errors.count, "error") %> prohibited this game_source from being saved:</h2>

      <ul>
      <% @game_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_sources/edit.html.erb
<h1>Editing game_source</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_source %> |
<%= link_to 'Back', game_sources_path %>

app/views/game_sources/index.html.erb
<h1>Listing game_sources</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @game_sources.each do |game_source| %>
  <tr>
    <td><%= link_to 'Show', game_source %></td>
    <td><%= link_to 'Edit', edit_game_source_path(game_source) %></td>
    <td><%= link_to 'Destroy', game_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game source', new_game_source_path %>

app/views/game_sources/new.html.erb
<h1>New game_source</h1>

<%= render 'form' %>

<%= link_to 'Back', game_sources_path %>

app/views/game_sources/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_game_source_path(@game_source) %> |
<%= link_to 'Back', game_sources_path %>